//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalogixDemoClient.MetalogixWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyWcfItem", Namespace="http://schemas.datacontract.org/2004/07/MetalogixDemoService")]
    [System.SerializableAttribute()]
    public partial class CompanyWcfItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyTypeEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem CompanyTypeItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyTypeEnum {
            get {
                return this.CompanyTypeEnumField;
            }
            set {
                if ((this.CompanyTypeEnumField.Equals(value) != true)) {
                    this.CompanyTypeEnumField = value;
                    this.RaisePropertyChanged("CompanyTypeEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem CompanyTypeItem {
            get {
                return this.CompanyTypeItemField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyTypeItemField, value) != true)) {
                    this.CompanyTypeItemField = value;
                    this.RaisePropertyChanged("CompanyTypeItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContryCode {
            get {
                return this.ContryCodeField;
            }
            set {
                if ((this.ContryCodeField.Equals(value) != true)) {
                    this.ContryCodeField = value;
                    this.RaisePropertyChanged("ContryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyWcfTypeItem", Namespace="http://schemas.datacontract.org/2004/07/MetalogixDemoService")]
    [System.SerializableAttribute()]
    public partial class CompanyWcfTypeItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetalogixWcfService.IMetalogixDemoService")]
    public interface IMetalogixDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetData", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetDataResponse")]
        MetalogixDemoClient.MetalogixWcfService.GetDataResponse GetData(MetalogixDemoClient.MetalogixWcfService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetData", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetDataResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.GetDataResponse> GetDataAsync(MetalogixDemoClient.MetalogixWcfService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetAllCompanies", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetAllCompaniesResponse")]
        MetalogixDemoClient.MetalogixWcfService.GetAllCompaniesResponse GetAllCompanies(MetalogixDemoClient.MetalogixWcfService.GetAllCompaniesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetAllCompanies", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetAllCompaniesResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.GetAllCompaniesResponse> GetAllCompaniesAsync(MetalogixDemoClient.MetalogixWcfService.GetAllCompaniesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/UpdateCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/UpdateCompanyResponse")]
        MetalogixDemoClient.MetalogixWcfService.UpdateCompanyResponse UpdateCompany(MetalogixDemoClient.MetalogixWcfService.UpdateCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/UpdateCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/UpdateCompanyResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.UpdateCompanyResponse> UpdateCompanyAsync(MetalogixDemoClient.MetalogixWcfService.UpdateCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/AddCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/AddCompanyResponse")]
        MetalogixDemoClient.MetalogixWcfService.AddCompanyResponse AddCompany(MetalogixDemoClient.MetalogixWcfService.AddCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/AddCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/AddCompanyResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.AddCompanyResponse> AddCompanyAsync(MetalogixDemoClient.MetalogixWcfService.AddCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetCompanyResponse")]
        MetalogixDemoClient.MetalogixWcfService.GetCompanyResponse GetCompany(MetalogixDemoClient.MetalogixWcfService.GetCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetCompanyResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.GetCompanyResponse> GetCompanyAsync(MetalogixDemoClient.MetalogixWcfService.GetCompanyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Action<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem, System.Exception> callback;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(System.Action<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem, System.Exception> callback) {
            this.callback = callback;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse {
        
        public GetDataResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCompanies", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllCompaniesRequest {
        
        public GetAllCompaniesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCompaniesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllCompaniesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem[] GetAllCompaniesResult;
        
        public GetAllCompaniesResponse() {
        }
        
        public GetAllCompaniesResponse(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem[] GetAllCompaniesResult) {
            this.GetAllCompaniesResult = GetAllCompaniesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCompany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company;
        
        public UpdateCompanyRequest() {
        }
        
        public UpdateCompanyRequest(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company) {
            this.company = company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCompanyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateCompanyResult;
        
        public UpdateCompanyResponse() {
        }
        
        public UpdateCompanyResponse(string UpdateCompanyResult) {
            this.UpdateCompanyResult = UpdateCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCompany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company;
        
        public AddCompanyRequest() {
        }
        
        public AddCompanyRequest(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company) {
            this.company = company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCompanyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddCompanyResult;
        
        public AddCompanyResponse() {
        }
        
        public AddCompanyResponse(string AddCompanyResult) {
            this.AddCompanyResult = AddCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string companyType;
        
        public GetCompanyRequest() {
        }
        
        public GetCompanyRequest(int Id, string companyName, string countryCode, string companyType) {
            this.Id = Id;
            this.companyName = companyName;
            this.countryCode = countryCode;
            this.companyType = companyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem GetCompanyResult;
        
        public GetCompanyResponse() {
        }
        
        public GetCompanyResponse(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem GetCompanyResult) {
            this.GetCompanyResult = GetCompanyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMetalogixDemoServiceChannel : MetalogixDemoClient.MetalogixWcfService.IMetalogixDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetalogixDemoServiceClient : System.ServiceModel.ClientBase<MetalogixDemoClient.MetalogixWcfService.IMetalogixDemoService>, MetalogixDemoClient.MetalogixWcfService.IMetalogixDemoService {
        
        public MetalogixDemoServiceClient() {
        }
        
        public MetalogixDemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetalogixDemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetalogixDemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetalogixDemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MetalogixDemoClient.MetalogixWcfService.GetDataResponse GetData(MetalogixDemoClient.MetalogixWcfService.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.GetDataResponse> GetDataAsync(MetalogixDemoClient.MetalogixWcfService.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public MetalogixDemoClient.MetalogixWcfService.GetAllCompaniesResponse GetAllCompanies(MetalogixDemoClient.MetalogixWcfService.GetAllCompaniesRequest request) {
            return base.Channel.GetAllCompanies(request);
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.GetAllCompaniesResponse> GetAllCompaniesAsync(MetalogixDemoClient.MetalogixWcfService.GetAllCompaniesRequest request) {
            return base.Channel.GetAllCompaniesAsync(request);
        }
        
        public MetalogixDemoClient.MetalogixWcfService.UpdateCompanyResponse UpdateCompany(MetalogixDemoClient.MetalogixWcfService.UpdateCompanyRequest request) {
            return base.Channel.UpdateCompany(request);
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.UpdateCompanyResponse> UpdateCompanyAsync(MetalogixDemoClient.MetalogixWcfService.UpdateCompanyRequest request) {
            return base.Channel.UpdateCompanyAsync(request);
        }
        
        public MetalogixDemoClient.MetalogixWcfService.AddCompanyResponse AddCompany(MetalogixDemoClient.MetalogixWcfService.AddCompanyRequest request) {
            return base.Channel.AddCompany(request);
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.AddCompanyResponse> AddCompanyAsync(MetalogixDemoClient.MetalogixWcfService.AddCompanyRequest request) {
            return base.Channel.AddCompanyAsync(request);
        }
        
        public MetalogixDemoClient.MetalogixWcfService.GetCompanyResponse GetCompany(MetalogixDemoClient.MetalogixWcfService.GetCompanyRequest request) {
            return base.Channel.GetCompany(request);
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.GetCompanyResponse> GetCompanyAsync(MetalogixDemoClient.MetalogixWcfService.GetCompanyRequest request) {
            return base.Channel.GetCompanyAsync(request);
        }
    }
}
