//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalogixWpfClientTest.MetalogixWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetalogixWcfService.IMetalogixDemoService")]
    public interface IMetalogixDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetData", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetDataResponse")]
        void GetData(System.Action<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem, System.Exception> callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetData", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetDataResponse")]
        System.Threading.Tasks.Task GetDataAsync(System.Action<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem, System.Exception> callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetAllCompanies", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetAllCompaniesResponse")]
        MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem[] GetAllCompanies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetAllCompanies", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetAllCompaniesResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem[]> GetAllCompaniesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/UpdateCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/UpdateCompanyResponse")]
        string UpdateCompany(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/UpdateCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/UpdateCompanyResponse")]
        System.Threading.Tasks.Task<string> UpdateCompanyAsync(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/AddCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/AddCompanyResponse")]
        string AddCompany(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/AddCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/AddCompanyResponse")]
        System.Threading.Tasks.Task<string> AddCompanyAsync(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetCompanyResponse")]
        MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem GetCompany(int Id, string companyName, string countryCode, string companyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetCompany", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetCompanyResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem> GetCompanyAsync(int Id, string companyName, string countryCode, string companyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetAllTypeData", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetAllTypeDataResponse")]
        MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem[] GetAllTypeData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetAllTypeData", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetAllTypeDataResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem[]> GetAllTypeDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetTypeData", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetTypeDataResponse")]
        MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem GetTypeData(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetalogixDemoService/GetTypeData", ReplyAction="http://tempuri.org/IMetalogixDemoService/GetTypeDataResponse")]
        System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem> GetTypeDataAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMetalogixDemoServiceChannel : MetalogixWpfClientTest.MetalogixWcfService.IMetalogixDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetalogixDemoServiceClient : System.ServiceModel.ClientBase<MetalogixWpfClientTest.MetalogixWcfService.IMetalogixDemoService>, MetalogixWpfClientTest.MetalogixWcfService.IMetalogixDemoService {
        
        public MetalogixDemoServiceClient() {
        }
        
        public MetalogixDemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetalogixDemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetalogixDemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetalogixDemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetData(System.Action<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem, System.Exception> callback) {
            base.Channel.GetData(callback);
        }
        
        public System.Threading.Tasks.Task GetDataAsync(System.Action<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem, System.Exception> callback) {
            return base.Channel.GetDataAsync(callback);
        }
        
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem[] GetAllCompanies() {
            return base.Channel.GetAllCompanies();
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem[]> GetAllCompaniesAsync() {
            return base.Channel.GetAllCompaniesAsync();
        }
        
        public string UpdateCompany(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company) {
            return base.Channel.UpdateCompany(company);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCompanyAsync(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company) {
            return base.Channel.UpdateCompanyAsync(company);
        }
        
        public string AddCompany(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company) {
            return base.Channel.AddCompany(company);
        }
        
        public System.Threading.Tasks.Task<string> AddCompanyAsync(MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem company) {
            return base.Channel.AddCompanyAsync(company);
        }
        
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem GetCompany(int Id, string companyName, string countryCode, string companyType) {
            return base.Channel.GetCompany(Id, companyName, countryCode, companyType);
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.CompanyWcfItem> GetCompanyAsync(int Id, string companyName, string countryCode, string companyType) {
            return base.Channel.GetCompanyAsync(Id, companyName, countryCode, companyType);
        }
        
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem[] GetAllTypeData() {
            return base.Channel.GetAllTypeData();
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem[]> GetAllTypeDataAsync() {
            return base.Channel.GetAllTypeDataAsync();
        }
        
        public MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem GetTypeData(int ID) {
            return base.Channel.GetTypeData(ID);
        }
        
        public System.Threading.Tasks.Task<MetalogixDemoClient.MetalogixWcfService.CompanyWcfTypeItem> GetTypeDataAsync(int ID) {
            return base.Channel.GetTypeDataAsync(ID);
        }
    }
}
